// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB-XvyB1nuJWVOwNkZ4I9tNfjIMV-QdDA',
    appId: '1:813754941979:web:e1064f2ffc589d22b82ebe',
    messagingSenderId: '813754941979',
    projectId: 'smartmoney-2b043',
    authDomain: 'smartmoney-2b043.firebaseapp.com',
    storageBucket: 'smartmoney-2b043.appspot.com',
    measurementId: 'G-1SS4TFNXH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjS_563__u_Os1SsHGoLDVk7U8GihvNT8',
    appId: '1:813754941979:android:352ce8df2e6172b1b82ebe',
    messagingSenderId: '813754941979',
    projectId: 'smartmoney-2b043',
    storageBucket: 'smartmoney-2b043.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuARVu3GV9EsRgHzMrPD9vpKoBu0tHGsM',
    appId: '1:813754941979:ios:328ca3515e3d34cfb82ebe',
    messagingSenderId: '813754941979',
    projectId: 'smartmoney-2b043',
    storageBucket: 'smartmoney-2b043.appspot.com',
    iosClientId: '813754941979-sa5mu94dqqouhhek1tf6u1f4837b0pbu.apps.googleusercontent.com',
    iosBundleId: 'com.whlinks6633.smartmoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuARVu3GV9EsRgHzMrPD9vpKoBu0tHGsM',
    appId: '1:813754941979:ios:328ca3515e3d34cfb82ebe',
    messagingSenderId: '813754941979',
    projectId: 'smartmoney-2b043',
    storageBucket: 'smartmoney-2b043.appspot.com',
    iosClientId: '813754941979-sa5mu94dqqouhhek1tf6u1f4837b0pbu.apps.googleusercontent.com',
    iosBundleId: 'com.whlinks6633.smartmoney',
  );
}
